language: ruby
rvm:
  - 2.6.3
before_script:
 - chmod +x ./_script/cibuild

script: ./_script/cibuild

deploy:
  provider: pages
  local-dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false
  
branches:
  only:
  - master
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # Route your build to the container-based infrastructure for a faster build

cache: bundler # Caching bundler gem packages will speed up build

notifications:
  email: false